//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/awslabs/operatorpkg/status"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *HCloudNodeClass) DeepCopyInto(out *HCloudNodeClass) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopyObject implements runtime.Object.
func (in *HCloudNodeClass) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopy creates a deep copy of HCloudNodeClass.
func (in *HCloudNodeClass) DeepCopy() *HCloudNodeClass {
	if in == nil {
		return nil
	}
	out := new(HCloudNodeClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *HCloudNodeClassList) DeepCopyInto(out *HCloudNodeClassList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HCloudNodeClass, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopyObject implements runtime.Object.
func (in *HCloudNodeClassList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopy creates a deep copy of HCloudNodeClassList.
func (in *HCloudNodeClassList) DeepCopy() *HCloudNodeClassList {
	if in == nil {
		return nil
	}
	out := new(HCloudNodeClassList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *HCloudNodeClassSpec) DeepCopyInto(out *HCloudNodeClassSpec) {
	*out = *in
	if in.Locations != nil {
		in, out := &in.Locations, &out.Locations
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.ImageSelector = in.ImageSelector
	if in.FirewallIDs != nil {
		in, out := &in.FirewallIDs, &out.FirewallIDs
		*out = make([]int64, len(*in))
		copy(*out, *in)
	}
	if in.SSHKeyIDs != nil {
		in, out := &in.SSHKeyIDs, &out.SSHKeyIDs
		*out = make([]int64, len(*in))
		copy(*out, *in)
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy creates a deep copy of HCloudNodeClassSpec.
func (in *HCloudNodeClassSpec) DeepCopy() *HCloudNodeClassSpec {
	if in == nil {
		return nil
	}
	out := new(HCloudNodeClassSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *HCloudNodeClassStatus) DeepCopyInto(out *HCloudNodeClassStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]status.Condition, len(*in))
		copy(*out, *in)
	}
	if in.ResolvedImages != nil {
		in, out := &in.ResolvedImages, &out.ResolvedImages
		*out = make([]ResolvedImage, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy creates a deep copy of HCloudNodeClassStatus.
func (in *HCloudNodeClassStatus) DeepCopy() *HCloudNodeClassStatus {
	if in == nil {
		return nil
	}
	out := new(HCloudNodeClassStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *ImageSelector) DeepCopyInto(out *ImageSelector) {
	*out = *in
}

// DeepCopy creates a deep copy of ImageSelector.
func (in *ImageSelector) DeepCopy() *ImageSelector {
	if in == nil {
		return nil
	}
	out := new(ImageSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *ResolvedImage) DeepCopyInto(out *ResolvedImage) {
	*out = *in
}

// DeepCopy creates a deep copy of ResolvedImage.
func (in *ResolvedImage) DeepCopy() *ResolvedImage {
	if in == nil {
		return nil
	}
	out := new(ResolvedImage)
	in.DeepCopyInto(out)
	return out
}
