//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/awslabs/operatorpkg/status"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HCloudNodeClass) DeepCopyInto(out *HCloudNodeClass) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HCloudNodeClass.
func (in *HCloudNodeClass) DeepCopy() *HCloudNodeClass {
	if in == nil {
		return nil
	}
	out := new(HCloudNodeClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HCloudNodeClass) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HCloudNodeClassList) DeepCopyInto(out *HCloudNodeClassList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HCloudNodeClass, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HCloudNodeClassList.
func (in *HCloudNodeClassList) DeepCopy() *HCloudNodeClassList {
	if in == nil {
		return nil
	}
	out := new(HCloudNodeClassList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HCloudNodeClassList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HCloudNodeClassSpec) DeepCopyInto(out *HCloudNodeClassSpec) {
	*out = *in
	if in.Locations != nil {
		in, out := &in.Locations, &out.Locations
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.ImageSelector = in.ImageSelector
	if in.FirewallIDs != nil {
		in, out := &in.FirewallIDs, &out.FirewallIDs
		*out = make([]int64, len(*in))
		copy(*out, *in)
	}
	if in.SSHKeyIDs != nil {
		in, out := &in.SSHKeyIDs, &out.SSHKeyIDs
		*out = make([]int64, len(*in))
		copy(*out, *in)
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.EnablePublicIPv4 != nil {
		in, out := &in.EnablePublicIPv4, &out.EnablePublicIPv4
		*out = new(bool)
		**out = **in
	}
	if in.EnablePublicIPv6 != nil {
		in, out := &in.EnablePublicIPv6, &out.EnablePublicIPv6
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HCloudNodeClassSpec.
func (in *HCloudNodeClassSpec) DeepCopy() *HCloudNodeClassSpec {
	if in == nil {
		return nil
	}
	out := new(HCloudNodeClassSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HCloudNodeClassStatus) DeepCopyInto(out *HCloudNodeClassStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]status.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ResolvedImages != nil {
		in, out := &in.ResolvedImages, &out.ResolvedImages
		*out = make([]ResolvedImage, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HCloudNodeClassStatus.
func (in *HCloudNodeClassStatus) DeepCopy() *HCloudNodeClassStatus {
	if in == nil {
		return nil
	}
	out := new(HCloudNodeClassStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageSelector) DeepCopyInto(out *ImageSelector) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageSelector.
func (in *ImageSelector) DeepCopy() *ImageSelector {
	if in == nil {
		return nil
	}
	out := new(ImageSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResolvedImage) DeepCopyInto(out *ResolvedImage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResolvedImage.
func (in *ResolvedImage) DeepCopy() *ResolvedImage {
	if in == nil {
		return nil
	}
	out := new(ResolvedImage)
	in.DeepCopyInto(out)
	return out
}
