{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "karpenter-hetzner.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "karpenter-hetzner.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "karpenter-hetzner.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http-metrics
      interval: {{ .Values.serviceMonitor.interval }}
      path: /metrics
{{- end }}
