{{- if .Values.serviceMonitor.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "karpenter-hetzner.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "karpenter-hetzner.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "karpenter-hetzner.selectorLabels" . | nindent 4 }}
  ports:
    - name: http-metrics
      port: {{ .Values.metrics.port }}
      targetPort: http-metrics
      protocol: TCP
{{- end }}
